"""Create the frozen Replay Analyzer V2 SQLite persistence baseline."""

from __future__ import annotations

from alembic import op

revision = "0001_replay_analyzer_v2"
down_revision = None
branch_labels = None
depends_on = None

TABLE_DDL: tuple[str, ...] = (
    r"""CREATE TABLE managed_assets (
	sha256 VARCHAR(64) NOT NULL,
	kind VARCHAR(64) NOT NULL,
	relative_path TEXT NOT NULL,
	size_bytes INTEGER NOT NULL,
	media_type VARCHAR(255),
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_managed_assets_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_managed_assets PRIMARY KEY (id),
	CONSTRAINT ck_managed_assets_sha256_lowercase_sha256 CHECK (length(sha256) = 64 AND sha256 = lower(sha256) AND sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_managed_assets_size_bytes_nonnegative CHECK (size_bytes >= 0),
	CONSTRAINT ck_managed_assets_relative_path_product_relative CHECK (length(relative_path) > 0 AND substr(relative_path, 1, 1) <> '/' AND substr(relative_path, -1, 1) <> '/' AND instr(relative_path, '\') = 0 AND instr(relative_path, ':') = 0 AND instr(relative_path, char(0)) = 0 AND instr(relative_path, '//') = 0 AND relative_path NOT IN ('.', '..') AND relative_path NOT LIKE './%' AND relative_path NOT LIKE '../%' AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/../%' AND relative_path NOT LIKE '%/.' AND relative_path NOT LIKE '%/..'),
	CONSTRAINT uq_managed_assets_sha256 UNIQUE (sha256),
	CONSTRAINT uq_managed_assets_relative_path UNIQUE (relative_path),
	CONSTRAINT uq_managed_assets_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE players (
	display_name TEXT NOT NULL,
	identity_revision INTEGER NOT NULL,
	updated_at DATETIME NOT NULL,
	retired_at DATETIME,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_players_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_players PRIMARY KEY (id),
	CONSTRAINT ck_players_identity_revision_nonnegative CHECK (identity_revision >= 0),
	CONSTRAINT uq_players_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE maps (
	content_sha256 VARCHAR(64) NOT NULL,
	manifest_asset_id INTEGER NOT NULL,
	schema_version INTEGER NOT NULL,
	engine_data_identity VARCHAR(255) NOT NULL,
	map_identity VARCHAR(255) NOT NULL,
	display_name TEXT,
	exporter_version VARCHAR(255) NOT NULL,
	min_x FLOAT NOT NULL,
	min_y FLOAT NOT NULL,
	min_z FLOAT NOT NULL,
	max_x FLOAT NOT NULL,
	max_y FLOAT NOT NULL,
	max_z FLOAT NOT NULL,
	pathing_width INTEGER NOT NULL,
	pathing_height INTEGER NOT NULL,
	pathing_cell_size FLOAT NOT NULL,
	terrain_width INTEGER NOT NULL,
	terrain_height INTEGER NOT NULL,
	terrain_cell_size FLOAT NOT NULL,
	metadata_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_maps_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_maps PRIMARY KEY (id),
	CONSTRAINT ck_maps_content_sha256_lowercase_sha256 CHECK (length(content_sha256) = 64 AND content_sha256 = lower(content_sha256) AND content_sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_maps_schema_version_nonnegative CHECK (schema_version >= 0),
	CONSTRAINT ck_maps_pathing_dimensions_nonnegative CHECK (pathing_width >= 0 AND pathing_height >= 0),
	CONSTRAINT ck_maps_terrain_dimensions_nonnegative CHECK (terrain_width >= 0 AND terrain_height >= 0),
	CONSTRAINT ck_maps_cell_sizes_positive CHECK (pathing_cell_size > 0 AND terrain_cell_size > 0),
	CONSTRAINT uq_maps_content_sha256 UNIQUE (content_sha256),
	CONSTRAINT fk_maps_manifest_asset_id_managed_assets FOREIGN KEY(manifest_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT uq_maps_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE player_aliases (
	player_id INTEGER NOT NULL,
	namespace VARCHAR(64) NOT NULL,
	normalized_name TEXT NOT NULL,
	original_name TEXT NOT NULL,
	external_subject TEXT,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_player_aliases_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_player_aliases PRIMARY KEY (id),
	CONSTRAINT uq_player_aliases_namespace_normalized_name UNIQUE (namespace, normalized_name),
	CONSTRAINT fk_player_aliases_player_id_players FOREIGN KEY(player_id) REFERENCES players (id) ON DELETE CASCADE,
	CONSTRAINT uq_player_aliases_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE longitudinal_runs (
	run_id VARCHAR(36) NOT NULL CONSTRAINT ck_longitudinal_runs_run_id_lowercase_uuid CHECK (length(run_id) = 36 AND run_id = lower(run_id) AND substr(run_id, 9, 1) = '-' AND substr(run_id, 14, 1) = '-' AND substr(run_id, 19, 1) = '-' AND substr(run_id, 24, 1) = '-' AND length(replace(run_id, '-', '')) = 32 AND replace(run_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	player_id INTEGER NOT NULL,
	identity_revision INTEGER NOT NULL,
	analyzer_name VARCHAR(255) NOT NULL,
	analyzer_version VARCHAR(255) NOT NULL,
	segment_key_json TEXT NOT NULL,
	settings_json TEXT NOT NULL,
	input_digest VARCHAR(64) NOT NULL,
	cache_key VARCHAR(64) NOT NULL,
	status VARCHAR(32) NOT NULL,
	created_at DATETIME NOT NULL,
	completed_at DATETIME,
	error_json TEXT,
	id INTEGER NOT NULL,
	CONSTRAINT pk_longitudinal_runs PRIMARY KEY (id),
	CONSTRAINT ck_longitudinal_runs_input_digest_lowercase_sha256 CHECK (length(input_digest) = 64 AND input_digest = lower(input_digest) AND input_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_longitudinal_runs_cache_key_lowercase_sha256 CHECK (length(cache_key) = 64 AND cache_key = lower(cache_key) AND cache_key NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_longitudinal_runs_identity_revision_nonnegative CHECK (identity_revision >= 0),
	CONSTRAINT ck_longitudinal_runs_status_valid CHECK (status IN ('pending','running','succeeded','failed')),
	CONSTRAINT uq_longitudinal_runs_run_id UNIQUE (run_id),
	CONSTRAINT fk_longitudinal_runs_player_id_players FOREIGN KEY(player_id) REFERENCES players (id) ON DELETE CASCADE
)""",
    r"""CREATE TABLE map_resources (
	map_id INTEGER NOT NULL,
	stable_key VARCHAR(255) NOT NULL,
	resource_kind VARCHAR(64) NOT NULL,
	source_object_id INTEGER,
	template_name VARCHAR(255),
	owner_player_index INTEGER,
	amount FLOAT,
	x FLOAT,
	y FLOAT,
	z FLOAT,
	payload_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_map_resources PRIMARY KEY (id),
	CONSTRAINT uq_map_resources_map_stable_key UNIQUE (map_id, stable_key),
	CONSTRAINT ck_map_resources_source_object_id_nonnegative CHECK (source_object_id IS NULL OR source_object_id >= 0),
	CONSTRAINT ck_map_resources_owner_player_index_nonnegative CHECK (owner_player_index IS NULL OR owner_player_index >= 0),
	CONSTRAINT ck_map_resources_amount_nonnegative CHECK (amount IS NULL OR amount >= 0),
	CONSTRAINT fk_map_resources_map_id_maps FOREIGN KEY(map_id) REFERENCES maps (id) ON DELETE CASCADE
)""",
    r"""CREATE TABLE map_regions (
	map_id INTEGER NOT NULL,
	stable_key VARCHAR(255) NOT NULL,
	region_kind VARCHAR(64) NOT NULL,
	label TEXT,
	geometry_json TEXT NOT NULL,
	relationships_json TEXT NOT NULL,
	payload_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_map_regions PRIMARY KEY (id),
	CONSTRAINT uq_map_regions_map_stable_key UNIQUE (map_id, stable_key),
	CONSTRAINT fk_map_regions_map_id_maps FOREIGN KEY(map_id) REFERENCES maps (id) ON DELETE CASCADE
)""",
    r"""CREATE TABLE replays (
	sha256 VARCHAR(64) NOT NULL,
	managed_asset_id INTEGER,
	map_id INTEGER,
	replay_name TEXT NOT NULL,
	version_string VARCHAR(64) NOT NULL,
	version_number INTEGER NOT NULL,
	frame_count INTEGER NOT NULL,
	start_time INTEGER NOT NULL,
	end_time INTEGER NOT NULL,
	exe_crc INTEGER NOT NULL,
	ini_crc INTEGER NOT NULL,
	map_crc INTEGER NOT NULL,
	map_name TEXT NOT NULL,
	seed INTEGER NOT NULL,
	starting_cash INTEGER,
	header_json TEXT NOT NULL,
	lifecycle_state VARCHAR(32) NOT NULL,
	updated_at DATETIME NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_replays_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_replays PRIMARY KEY (id),
	CONSTRAINT ck_replays_sha256_lowercase_sha256 CHECK (length(sha256) = 64 AND sha256 = lower(sha256) AND sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_replays_version_number_nonnegative CHECK (version_number >= 0),
	CONSTRAINT ck_replays_frame_count_nonnegative CHECK (frame_count >= 0),
	CONSTRAINT ck_replays_starting_cash_nonnegative CHECK (starting_cash IS NULL OR starting_cash >= 0),
	CONSTRAINT ck_replays_lifecycle_state_valid CHECK (lifecycle_state IN ('discovered','parsed','engine_verified','partial','desynced','unsupported','failed')),
	CONSTRAINT uq_replays_sha256 UNIQUE (sha256),
	CONSTRAINT fk_replays_managed_asset_id_managed_assets FOREIGN KEY(managed_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT fk_replays_map_id_maps FOREIGN KEY(map_id) REFERENCES maps (id) ON DELETE SET NULL,
	CONSTRAINT uq_replays_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE sources (
	replay_id INTEGER,
	source_kind VARCHAR(64) NOT NULL,
	original_locator TEXT NOT NULL,
	original_filename TEXT NOT NULL,
	strata_match_id VARCHAR(255),
	strata_source_user_token VARCHAR(255),
	file_size_bytes INTEGER,
	source_modified_at DATETIME,
	discovered_at DATETIME NOT NULL,
	provenance_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_sources_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_sources PRIMARY KEY (id),
	CONSTRAINT ck_sources_file_size_bytes_nonnegative CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
	CONSTRAINT fk_sources_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE SET NULL,
	CONSTRAINT uq_sources_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE parser_runs (
	run_id VARCHAR(36) NOT NULL CONSTRAINT ck_parser_runs_run_id_lowercase_uuid CHECK (length(run_id) = 36 AND run_id = lower(run_id) AND substr(run_id, 9, 1) = '-' AND substr(run_id, 14, 1) = '-' AND substr(run_id, 19, 1) = '-' AND substr(run_id, 24, 1) = '-' AND length(replace(run_id, '-', '')) = 32 AND replace(run_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	replay_id INTEGER NOT NULL,
	parser_version VARCHAR(255) NOT NULL,
	schema_version INTEGER NOT NULL,
	input_sha256 VARCHAR(64) NOT NULL,
	result_sha256 VARCHAR(64),
	status VARCHAR(32) NOT NULL,
	completion_status VARCHAR(32),
	command_stream_offset INTEGER,
	end_offset INTEGER,
	warnings_json TEXT NOT NULL,
	error_json TEXT,
	started_at DATETIME NOT NULL,
	completed_at DATETIME,
	id INTEGER NOT NULL,
	CONSTRAINT pk_parser_runs PRIMARY KEY (id),
	CONSTRAINT ck_parser_runs_input_sha256_lowercase_sha256 CHECK (length(input_sha256) = 64 AND input_sha256 = lower(input_sha256) AND input_sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_parser_runs_result_sha256_lowercase_sha256 CHECK (length(result_sha256) = 64 AND result_sha256 = lower(result_sha256) AND result_sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_parser_runs_status_valid CHECK (status IN ('pending','running','succeeded','failed')),
	CONSTRAINT ck_parser_runs_completion_status_valid CHECK (completion_status IS NULL OR completion_status IN ('complete','truncated','unsupported','failed')),
	CONSTRAINT ck_parser_runs_schema_version_nonnegative CHECK (schema_version >= 0),
	CONSTRAINT ck_parser_runs_command_stream_offset_nonnegative CHECK (command_stream_offset IS NULL OR command_stream_offset >= 0),
	CONSTRAINT ck_parser_runs_end_offset_nonnegative CHECK (end_offset IS NULL OR end_offset >= 0),
	CONSTRAINT uq_parser_runs_run_id UNIQUE (run_id),
	CONSTRAINT fk_parser_runs_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE
)""",
    r"""CREATE TABLE telemetry_runs (
	run_id VARCHAR(36) NOT NULL CONSTRAINT ck_telemetry_runs_run_id_lowercase_uuid CHECK (length(run_id) = 36 AND run_id = lower(run_id) AND substr(run_id, 9, 1) = '-' AND substr(run_id, 14, 1) = '-' AND substr(run_id, 19, 1) = '-' AND substr(run_id, 24, 1) = '-' AND length(replace(run_id, '-', '')) = 32 AND replace(run_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	replay_id INTEGER NOT NULL,
	trace_asset_id INTEGER,
	catalog_asset_id INTEGER,
	map_asset_id INTEGER,
	map_id INTEGER,
	schema_version INTEGER NOT NULL,
	engine_build VARCHAR(255) NOT NULL,
	engine_executable_sha256 VARCHAR(64),
	settings_json TEXT NOT NULL,
	status VARCHAR(32) NOT NULL,
	runner_status VARCHAR(64) NOT NULL,
	strategy_analysis_scope VARCHAR(64),
	process_exit_code INTEGER,
	final_frame INTEGER,
	command_count INTEGER,
	trace_sha256 VARCHAR(64),
	diagnostics_json TEXT NOT NULL,
	started_at DATETIME NOT NULL,
	completed_at DATETIME,
	id INTEGER NOT NULL,
	CONSTRAINT pk_telemetry_runs PRIMARY KEY (id),
	CONSTRAINT ck_telemetry_runs_engine_executable_sha256_lowercase_sha256 CHECK (length(engine_executable_sha256) = 64 AND engine_executable_sha256 = lower(engine_executable_sha256) AND engine_executable_sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_telemetry_runs_trace_sha256_lowercase_sha256 CHECK (length(trace_sha256) = 64 AND trace_sha256 = lower(trace_sha256) AND trace_sha256 NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_telemetry_runs_schema_version_nonnegative CHECK (schema_version >= 0),
	CONSTRAINT ck_telemetry_runs_status_valid CHECK (status IN ('pending','running','succeeded','failed')),
	CONSTRAINT ck_telemetry_runs_process_exit_code_nonnegative CHECK (process_exit_code IS NULL OR process_exit_code >= 0),
	CONSTRAINT ck_telemetry_runs_final_frame_nonnegative CHECK (final_frame IS NULL OR final_frame >= 0),
	CONSTRAINT ck_telemetry_runs_command_count_nonnegative CHECK (command_count IS NULL OR command_count >= 0),
	CONSTRAINT uq_telemetry_runs_run_id UNIQUE (run_id),
	CONSTRAINT fk_telemetry_runs_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_telemetry_runs_trace_asset_id_managed_assets FOREIGN KEY(trace_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT fk_telemetry_runs_catalog_asset_id_managed_assets FOREIGN KEY(catalog_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT fk_telemetry_runs_map_asset_id_managed_assets FOREIGN KEY(map_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT fk_telemetry_runs_map_id_maps FOREIGN KEY(map_id) REFERENCES maps (id) ON DELETE SET NULL
)""",
    r"""CREATE TABLE jobs (
	replay_id INTEGER,
	stage VARCHAR(64) NOT NULL,
	component_version VARCHAR(255) NOT NULL,
	idempotency_key TEXT NOT NULL,
	status VARCHAR(32) NOT NULL,
	priority INTEGER NOT NULL,
	attempt_count INTEGER NOT NULL,
	max_attempts INTEGER NOT NULL,
	available_at DATETIME NOT NULL,
	lease_owner VARCHAR(255),
	lease_expires_at DATETIME,
	started_at DATETIME,
	completed_at DATETIME,
	input_json TEXT NOT NULL,
	output_json TEXT,
	error_code VARCHAR(128),
	error_message TEXT,
	error_details_json TEXT,
	retryable BOOLEAN NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_jobs_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_jobs PRIMARY KEY (id),
	CONSTRAINT ck_jobs_status_valid CHECK (status IN ('pending','running','succeeded','failed')),
	CONSTRAINT ck_jobs_priority_nonnegative CHECK (priority >= 0),
	CONSTRAINT ck_jobs_attempts_nonnegative CHECK (attempt_count >= 0 AND max_attempts >= 0),
	CONSTRAINT ck_jobs_attempt_count_within_maximum CHECK (attempt_count <= max_attempts),
	CONSTRAINT ck_jobs_retryable_boolean CHECK (retryable IN (0, 1)),
	CONSTRAINT ck_jobs_lease_state_valid CHECK ((status = 'running' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status != 'running' AND lease_owner IS NULL AND lease_expires_at IS NULL)),
	CONSTRAINT fk_jobs_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE SET NULL,
	CONSTRAINT uq_jobs_idempotency_key UNIQUE (idempotency_key),
	CONSTRAINT uq_jobs_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE replay_players (
	replay_id INTEGER NOT NULL,
	parser_run_id INTEGER NOT NULL,
	player_id INTEGER,
	slot_index INTEGER NOT NULL,
	slot_kind VARCHAR(64) NOT NULL,
	original_name TEXT,
	normalized_name TEXT,
	player_index INTEGER,
	team_id INTEGER,
	faction VARCHAR(255),
	color VARCHAR(255),
	start_position INTEGER,
	result VARCHAR(64),
	observed_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_replay_players_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_replay_players PRIMARY KEY (id),
	CONSTRAINT uq_replay_players_parser_slot UNIQUE (parser_run_id, slot_index),
	CONSTRAINT ck_replay_players_slot_index_nonnegative CHECK (slot_index >= 0),
	CONSTRAINT ck_replay_players_player_index_nonnegative CHECK (player_index IS NULL OR player_index >= 0),
	CONSTRAINT fk_replay_players_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_replay_players_parser_run_id_parser_runs FOREIGN KEY(parser_run_id) REFERENCES parser_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_replay_players_player_id_players FOREIGN KEY(player_id) REFERENCES players (id) ON DELETE SET NULL,
	CONSTRAINT uq_replay_players_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE entities (
	telemetry_run_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	object_id INTEGER NOT NULL,
	template_name VARCHAR(255) NOT NULL,
	initial_owner_player_index INTEGER,
	initial_team_id INTEGER,
	kind_of_flags_json TEXT NOT NULL,
	creation_sequence INTEGER,
	creation_frame INTEGER,
	destruction_sequence INTEGER,
	destruction_frame INTEGER,
	observed_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_entities_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_entities PRIMARY KEY (id),
	CONSTRAINT uq_entities_run_object_id UNIQUE (telemetry_run_id, object_id),
	CONSTRAINT ck_entities_object_id_nonnegative CHECK (object_id >= 0),
	CONSTRAINT ck_entities_initial_owner_nonnegative CHECK (initial_owner_player_index IS NULL OR initial_owner_player_index >= 0),
	CONSTRAINT ck_entities_initial_team_nonnegative CHECK (initial_team_id IS NULL OR initial_team_id >= 0),
	CONSTRAINT ck_entities_creation_sequence_nonnegative CHECK (creation_sequence IS NULL OR creation_sequence >= 0),
	CONSTRAINT ck_entities_creation_frame_nonnegative CHECK (creation_frame IS NULL OR creation_frame >= 0),
	CONSTRAINT ck_entities_destruction_sequence_nonnegative CHECK (destruction_sequence IS NULL OR destruction_sequence >= 0),
	CONSTRAINT ck_entities_destruction_frame_nonnegative CHECK (destruction_frame IS NULL OR destruction_frame >= 0),
	CONSTRAINT fk_entities_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_entities_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT uq_entities_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE evidence_items (
	replay_id INTEGER NOT NULL,
	parser_run_id INTEGER,
	telemetry_run_id INTEGER,
	tier VARCHAR(32) NOT NULL,
	source_kind VARCHAR(64) NOT NULL,
	source_key TEXT NOT NULL,
	schema_version INTEGER NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_evidence_items_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_evidence_items PRIMARY KEY (id),
	CONSTRAINT uq_evidence_items_source_identity UNIQUE (source_kind, source_key),
	CONSTRAINT ck_evidence_items_tier_valid CHECK (tier IN ('observed','derived','inferred')),
	CONSTRAINT ck_evidence_items_schema_version_nonnegative CHECK (schema_version >= 0),
	CONSTRAINT fk_evidence_items_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_evidence_items_parser_run_id_parser_runs FOREIGN KEY(parser_run_id) REFERENCES parser_runs (id) ON DELETE RESTRICT,
	CONSTRAINT fk_evidence_items_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE RESTRICT,
	CONSTRAINT uq_evidence_items_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE job_dependencies (
	job_id INTEGER NOT NULL,
	depends_on_job_id INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_job_dependencies PRIMARY KEY (job_id, depends_on_job_id),
	CONSTRAINT ck_job_dependencies_not_self_edge CHECK (job_id != depends_on_job_id),
	CONSTRAINT fk_job_dependencies_job_id_jobs FOREIGN KEY(job_id) REFERENCES jobs (id) ON DELETE CASCADE,
	CONSTRAINT fk_job_dependencies_depends_on_job_id_jobs FOREIGN KEY(depends_on_job_id) REFERENCES jobs (id) ON DELETE CASCADE
)""",
    r"""CREATE TABLE replay_quality_issues (
	replay_id INTEGER NOT NULL,
	parser_run_id INTEGER,
	telemetry_run_id INTEGER,
	evidence_item_id INTEGER,
	stage VARCHAR(64) NOT NULL,
	issue_code VARCHAR(128) NOT NULL,
	severity VARCHAR(32) NOT NULL,
	details_json TEXT NOT NULL,
	detected_at DATETIME NOT NULL,
	resolved_at DATETIME,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_replay_quality_issues_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_replay_quality_issues PRIMARY KEY (id),
	CONSTRAINT fk_replay_quality_issues_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_replay_quality_issues_parser_run_id_parser_runs FOREIGN KEY(parser_run_id) REFERENCES parser_runs (id) ON DELETE RESTRICT,
	CONSTRAINT fk_replay_quality_issues_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE RESTRICT,
	CONSTRAINT fk_replay_quality_issues_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT,
	CONSTRAINT uq_replay_quality_issues_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE commands (
	parser_run_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER,
	command_index INTEGER NOT NULL,
	frame INTEGER NOT NULL,
	player_index INTEGER NOT NULL,
	message_type INTEGER NOT NULL,
	message_name VARCHAR(255),
	start_offset INTEGER NOT NULL,
	end_offset INTEGER NOT NULL,
	arguments_json TEXT NOT NULL,
	evidence_item_id INTEGER NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_commands PRIMARY KEY (id),
	CONSTRAINT uq_commands_parser_command_index UNIQUE (parser_run_id, command_index),
	CONSTRAINT uq_commands_evidence_item_id UNIQUE (evidence_item_id),
	CONSTRAINT ck_commands_command_index_nonnegative CHECK (command_index >= 0),
	CONSTRAINT ck_commands_frame_nonnegative CHECK (frame >= 0),
	CONSTRAINT ck_commands_player_index_nonnegative CHECK (player_index >= 0),
	CONSTRAINT ck_commands_message_type_nonnegative CHECK (message_type >= 0),
	CONSTRAINT ck_commands_offsets_valid CHECK (start_offset >= 0 AND end_offset > start_offset),
	CONSTRAINT fk_commands_parser_run_id_parser_runs FOREIGN KEY(parser_run_id) REFERENCES parser_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_commands_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_commands_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_commands_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT
)""",
    r"""CREATE TABLE telemetry_events (
	telemetry_run_id INTEGER NOT NULL,
	sequence INTEGER NOT NULL,
	frame INTEGER NOT NULL,
	logic_time_seconds FLOAT NOT NULL,
	schema_version INTEGER NOT NULL,
	event_type VARCHAR(255) NOT NULL,
	payload_json TEXT NOT NULL,
	raw_record_json TEXT NOT NULL,
	evidence_item_id INTEGER NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_telemetry_events PRIMARY KEY (id),
	CONSTRAINT uq_telemetry_events_run_sequence UNIQUE (telemetry_run_id, sequence),
	CONSTRAINT uq_telemetry_events_evidence_item_id UNIQUE (evidence_item_id),
	CONSTRAINT ck_telemetry_events_sequence_nonnegative CHECK (sequence >= 0),
	CONSTRAINT ck_telemetry_events_frame_nonnegative CHECK (frame >= 0),
	CONSTRAINT ck_telemetry_events_logic_time_seconds_nonnegative CHECK (logic_time_seconds >= 0),
	CONSTRAINT ck_telemetry_events_schema_version_nonnegative CHECK (schema_version >= 0),
	CONSTRAINT fk_telemetry_events_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_telemetry_events_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT
)""",
    r"""CREATE TABLE feature_sets (
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER,
	extractor_name VARCHAR(255) NOT NULL,
	extractor_version VARCHAR(255) NOT NULL,
	input_digest VARCHAR(64) NOT NULL,
	cache_key VARCHAR(64) NOT NULL,
	status VARCHAR(32) NOT NULL,
	settings_json TEXT NOT NULL,
	completed_at DATETIME,
	error_json TEXT,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_feature_sets_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_feature_sets PRIMARY KEY (id),
	CONSTRAINT ck_feature_sets_input_digest_lowercase_sha256 CHECK (length(input_digest) = 64 AND input_digest = lower(input_digest) AND input_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_feature_sets_cache_key_lowercase_sha256 CHECK (length(cache_key) = 64 AND cache_key = lower(cache_key) AND cache_key NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_feature_sets_status_valid CHECK (status IN ('pending','running','succeeded','failed')),
	CONSTRAINT fk_feature_sets_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_feature_sets_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT uq_feature_sets_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE analysis_runs (
	run_id VARCHAR(36) NOT NULL CONSTRAINT ck_analysis_runs_run_id_lowercase_uuid CHECK (length(run_id) = 36 AND run_id = lower(run_id) AND substr(run_id, 9, 1) = '-' AND substr(run_id, 14, 1) = '-' AND substr(run_id, 19, 1) = '-' AND substr(run_id, 24, 1) = '-' AND length(replace(run_id, '-', '')) = 32 AND replace(run_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	replay_id INTEGER,
	replay_player_id INTEGER,
	provider VARCHAR(64) NOT NULL,
	model_name VARCHAR(255) NOT NULL,
	model_digest VARCHAR(64) NOT NULL,
	prompt_version VARCHAR(255) NOT NULL,
	prompt_digest VARCHAR(64) NOT NULL,
	response_schema_version VARCHAR(255) NOT NULL,
	response_schema_digest VARCHAR(64) NOT NULL,
	settings_digest VARCHAR(64) NOT NULL,
	input_digest VARCHAR(64) NOT NULL,
	cache_key VARCHAR(64) NOT NULL,
	status VARCHAR(32) NOT NULL,
	raw_response_asset_id INTEGER,
	validated_response_json TEXT,
	diagnostics_json TEXT NOT NULL,
	error_json TEXT,
	created_at DATETIME NOT NULL,
	completed_at DATETIME,
	id INTEGER NOT NULL,
	CONSTRAINT pk_analysis_runs PRIMARY KEY (id),
	CONSTRAINT ck_analysis_runs_model_digest_lowercase_sha256 CHECK (length(model_digest) = 64 AND model_digest = lower(model_digest) AND model_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_analysis_runs_prompt_digest_lowercase_sha256 CHECK (length(prompt_digest) = 64 AND prompt_digest = lower(prompt_digest) AND prompt_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_analysis_runs_response_schema_digest_lowercase_sha256 CHECK (length(response_schema_digest) = 64 AND response_schema_digest = lower(response_schema_digest) AND response_schema_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_analysis_runs_settings_digest_lowercase_sha256 CHECK (length(settings_digest) = 64 AND settings_digest = lower(settings_digest) AND settings_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_analysis_runs_input_digest_lowercase_sha256 CHECK (length(input_digest) = 64 AND input_digest = lower(input_digest) AND input_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_analysis_runs_cache_key_lowercase_sha256 CHECK (length(cache_key) = 64 AND cache_key = lower(cache_key) AND cache_key NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_analysis_runs_status_valid CHECK (status IN ('pending','running','succeeded','failed','invalid','unavailable')),
	CONSTRAINT uq_analysis_runs_run_id UNIQUE (run_id),
	CONSTRAINT fk_analysis_runs_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_analysis_runs_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_analysis_runs_raw_response_asset_id_managed_assets FOREIGN KEY(raw_response_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT
)""",
    r"""CREATE TABLE longitudinal_results (
	longitudinal_run_id INTEGER NOT NULL,
	evidence_item_id INTEGER NOT NULL,
	result_name VARCHAR(255) NOT NULL,
	result_kind VARCHAR(64) NOT NULL,
	sample_count INTEGER NOT NULL,
	missing_count INTEGER NOT NULL,
	quality VARCHAR(32) NOT NULL,
	quality_reason TEXT,
	statistics_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_longitudinal_results_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_longitudinal_results PRIMARY KEY (id),
	CONSTRAINT uq_longitudinal_results_evidence_item_id UNIQUE (evidence_item_id),
	CONSTRAINT ck_longitudinal_results_counts_nonnegative CHECK (sample_count >= 0 AND missing_count >= 0),
	CONSTRAINT ck_longitudinal_results_quality_valid CHECK (quality IN ('available','unavailable','partial')),
	CONSTRAINT ck_longitudinal_results_unavailable_reason_required CHECK ((quality = 'unavailable' AND quality_reason IS NOT NULL) OR quality != 'unavailable'),
	CONSTRAINT fk_longitudinal_results_longitudinal_run_id_longitudinal_runs FOREIGN KEY(longitudinal_run_id) REFERENCES longitudinal_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_longitudinal_results_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT,
	CONSTRAINT uq_longitudinal_results_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE entity_samples (
	telemetry_run_id INTEGER NOT NULL,
	entity_id INTEGER NOT NULL,
	telemetry_event_id INTEGER NOT NULL,
	sequence INTEGER NOT NULL,
	frame INTEGER NOT NULL,
	x FLOAT NOT NULL,
	y FLOAT NOT NULL,
	z FLOAT NOT NULL,
	orientation FLOAT NOT NULL,
	speed FLOAT,
	layer VARCHAR(64),
	locomotor_name VARCHAR(255),
	order_type VARCHAR(255),
	path_goal_x FLOAT,
	path_goal_y FLOAT,
	path_goal_z FLOAT,
	current_state VARCHAR(255) NOT NULL,
	source VARCHAR(255) NOT NULL,
	sample_reason VARCHAR(255) NOT NULL,
	payload_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_entity_samples PRIMARY KEY (id),
	CONSTRAINT uq_entity_samples_telemetry_event_id UNIQUE (telemetry_event_id),
	CONSTRAINT uq_entity_samples_entity_sequence UNIQUE (entity_id, sequence),
	CONSTRAINT ck_entity_samples_sequence_nonnegative CHECK (sequence >= 0),
	CONSTRAINT ck_entity_samples_frame_nonnegative CHECK (frame >= 0),
	CONSTRAINT fk_entity_samples_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_entity_samples_entity_id_entities FOREIGN KEY(entity_id) REFERENCES entities (id) ON DELETE CASCADE,
	CONSTRAINT fk_entity_samples_telemetry_event_id_telemetry_events FOREIGN KEY(telemetry_event_id) REFERENCES telemetry_events (id) ON DELETE CASCADE
)""",
    r"""CREATE TABLE production_events (
	telemetry_run_id INTEGER NOT NULL,
	telemetry_event_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER,
	producer_entity_id INTEGER,
	frame INTEGER NOT NULL,
	event_type VARCHAR(255) NOT NULL,
	item_kind VARCHAR(64) NOT NULL,
	item_name VARCHAR(255) NOT NULL,
	production_id INTEGER,
	upgrade_id INTEGER,
	queue_position INTEGER,
	queued_frame INTEGER,
	terminal_frame INTEGER,
	cost FLOAT,
	quantity INTEGER NOT NULL,
	state VARCHAR(64) NOT NULL,
	payload_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_production_events PRIMARY KEY (id),
	CONSTRAINT uq_production_events_telemetry_event_id UNIQUE (telemetry_event_id),
	CONSTRAINT ck_production_events_frame_nonnegative CHECK (frame >= 0),
	CONSTRAINT ck_production_events_queue_position_nonnegative CHECK (queue_position IS NULL OR queue_position >= 0),
	CONSTRAINT ck_production_events_queued_frame_nonnegative CHECK (queued_frame IS NULL OR queued_frame >= 0),
	CONSTRAINT ck_production_events_terminal_frame_nonnegative CHECK (terminal_frame IS NULL OR terminal_frame >= 0),
	CONSTRAINT ck_production_events_cost_nonnegative CHECK (cost IS NULL OR cost >= 0),
	CONSTRAINT ck_production_events_quantity_nonnegative CHECK (quantity >= 0),
	CONSTRAINT fk_production_events_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_production_events_telemetry_event_id_telemetry_events FOREIGN KEY(telemetry_event_id) REFERENCES telemetry_events (id) ON DELETE CASCADE,
	CONSTRAINT fk_production_events_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_production_events_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_production_events_producer_entity_id_entities FOREIGN KEY(producer_entity_id) REFERENCES entities (id) ON DELETE SET NULL
)""",
    r"""CREATE TABLE economy_events (
	telemetry_run_id INTEGER NOT NULL,
	telemetry_event_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER,
	collector_entity_id INTEGER,
	source_entity_id INTEGER,
	dropoff_entity_id INTEGER,
	frame INTEGER NOT NULL,
	event_type VARCHAR(255) NOT NULL,
	balance_before FLOAT,
	amount_delta FLOAT,
	balance_after FLOAT,
	amount FLOAT,
	reason VARCHAR(255),
	location_x FLOAT,
	location_y FLOAT,
	location_z FLOAT,
	payload_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_economy_events PRIMARY KEY (id),
	CONSTRAINT uq_economy_events_telemetry_event_id UNIQUE (telemetry_event_id),
	CONSTRAINT ck_economy_events_frame_nonnegative CHECK (frame >= 0),
	CONSTRAINT fk_economy_events_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_economy_events_telemetry_event_id_telemetry_events FOREIGN KEY(telemetry_event_id) REFERENCES telemetry_events (id) ON DELETE CASCADE,
	CONSTRAINT fk_economy_events_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_economy_events_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_economy_events_collector_entity_id_entities FOREIGN KEY(collector_entity_id) REFERENCES entities (id) ON DELETE SET NULL,
	CONSTRAINT fk_economy_events_source_entity_id_entities FOREIGN KEY(source_entity_id) REFERENCES entities (id) ON DELETE SET NULL,
	CONSTRAINT fk_economy_events_dropoff_entity_id_entities FOREIGN KEY(dropoff_entity_id) REFERENCES entities (id) ON DELETE SET NULL
)""",
    r"""CREATE TABLE combat_events (
	telemetry_run_id INTEGER NOT NULL,
	telemetry_event_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	frame INTEGER NOT NULL,
	event_type VARCHAR(255) NOT NULL,
	attacker_entity_id INTEGER,
	victim_entity_id INTEGER,
	source_entity_id INTEGER,
	attacker_replay_player_id INTEGER,
	victim_replay_player_id INTEGER,
	weapon_name VARCHAR(255),
	damage_type VARCHAR(255),
	death_type VARCHAR(255),
	attempted_amount FLOAT,
	calculated_amount FLOAT,
	applied_amount FLOAT,
	health_before FLOAT,
	health_after FLOAT,
	killing_blow BOOLEAN,
	location_x FLOAT,
	location_y FLOAT,
	location_z FLOAT,
	payload_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_combat_events PRIMARY KEY (id),
	CONSTRAINT uq_combat_events_telemetry_event_id UNIQUE (telemetry_event_id),
	CONSTRAINT ck_combat_events_frame_nonnegative CHECK (frame >= 0),
	CONSTRAINT ck_combat_events_killing_blow_boolean CHECK (killing_blow IS NULL OR killing_blow IN (0, 1)),
	CONSTRAINT fk_combat_events_telemetry_run_id_telemetry_runs FOREIGN KEY(telemetry_run_id) REFERENCES telemetry_runs (id) ON DELETE CASCADE,
	CONSTRAINT fk_combat_events_telemetry_event_id_telemetry_events FOREIGN KEY(telemetry_event_id) REFERENCES telemetry_events (id) ON DELETE CASCADE,
	CONSTRAINT fk_combat_events_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_combat_events_attacker_entity_id_entities FOREIGN KEY(attacker_entity_id) REFERENCES entities (id) ON DELETE SET NULL,
	CONSTRAINT fk_combat_events_victim_entity_id_entities FOREIGN KEY(victim_entity_id) REFERENCES entities (id) ON DELETE SET NULL,
	CONSTRAINT fk_combat_events_source_entity_id_entities FOREIGN KEY(source_entity_id) REFERENCES entities (id) ON DELETE SET NULL,
	CONSTRAINT fk_combat_events_attacker_replay_player_id_replay_players FOREIGN KEY(attacker_replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_combat_events_victim_replay_player_id_replay_players FOREIGN KEY(victim_replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL
)""",
    r"""CREATE TABLE features (
	feature_set_id INTEGER NOT NULL,
	evidence_item_id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	value_type VARCHAR(32) NOT NULL,
	integer_value INTEGER,
	real_value FLOAT,
	text_value TEXT,
	boolean_value BOOLEAN,
	json_value TEXT,
	unit VARCHAR(64),
	scope_type VARCHAR(64) NOT NULL,
	scope_key VARCHAR(255) NOT NULL,
	replay_player_id INTEGER,
	team_id INTEGER,
	entity_id INTEGER,
	frame_start INTEGER NOT NULL,
	frame_end INTEGER NOT NULL,
	quality VARCHAR(32) NOT NULL,
	quality_reason TEXT,
	confidence FLOAT,
	explanation TEXT,
	details_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_features_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT pk_features PRIMARY KEY (id),
	CONSTRAINT uq_features_evidence_item_id UNIQUE (evidence_item_id),
	CONSTRAINT uq_features_logical_identity UNIQUE (feature_set_id, name, scope_type, scope_key, frame_start, frame_end),
	CONSTRAINT ck_features_value_type_valid CHECK (value_type IN ('integer','real','text','boolean','json')),
	CONSTRAINT ck_features_quality_valid CHECK (quality IN ('available','unavailable','partial')),
	CONSTRAINT ck_features_frame_window_valid CHECK (frame_start >= 0 AND frame_end >= frame_start),
	CONSTRAINT ck_features_confidence_bounded CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
	CONSTRAINT ck_features_boolean_value_boolean CHECK (boolean_value IS NULL OR boolean_value IN (0, 1)),
	CONSTRAINT ck_features_typed_value_matches_quality CHECK ((quality = 'unavailable' AND integer_value IS NULL AND real_value IS NULL AND text_value IS NULL AND boolean_value IS NULL AND json_value IS NULL AND quality_reason IS NOT NULL) OR (quality != 'unavailable' AND quality_reason IS NULL AND ((value_type = 'integer' AND integer_value IS NOT NULL AND real_value IS NULL AND text_value IS NULL AND boolean_value IS NULL AND json_value IS NULL) OR (value_type = 'real' AND integer_value IS NULL AND real_value IS NOT NULL AND text_value IS NULL AND boolean_value IS NULL AND json_value IS NULL) OR (value_type = 'text' AND integer_value IS NULL AND real_value IS NULL AND text_value IS NOT NULL AND boolean_value IS NULL AND json_value IS NULL) OR (value_type = 'boolean' AND integer_value IS NULL AND real_value IS NULL AND text_value IS NULL AND boolean_value IS NOT NULL AND json_value IS NULL) OR (value_type = 'json' AND integer_value IS NULL AND real_value IS NULL AND text_value IS NULL AND boolean_value IS NULL AND json_value IS NOT NULL)))),
	CONSTRAINT fk_features_feature_set_id_feature_sets FOREIGN KEY(feature_set_id) REFERENCES feature_sets (id) ON DELETE CASCADE,
	CONSTRAINT fk_features_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT,
	CONSTRAINT fk_features_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_features_entity_id_entities FOREIGN KEY(entity_id) REFERENCES entities (id) ON DELETE SET NULL,
	CONSTRAINT uq_features_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE strategy_assessments (
	evidence_item_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER,
	analysis_run_id INTEGER,
	method VARCHAR(32) NOT NULL,
	strategy_label VARCHAR(255) NOT NULL,
	phase VARCHAR(64) NOT NULL,
	taxonomy_version VARCHAR(255),
	rule_version VARCHAR(255),
	model_version VARCHAR(255),
	frame_start INTEGER NOT NULL,
	frame_end INTEGER NOT NULL,
	quality VARCHAR(32) NOT NULL,
	confidence FLOAT,
	details_json TEXT NOT NULL,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_strategy_assessments_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_strategy_assessments PRIMARY KEY (id),
	CONSTRAINT uq_strategy_assessments_evidence_item_id UNIQUE (evidence_item_id),
	CONSTRAINT ck_strategy_assessments_method_valid CHECK (method IN ('rule','statistical','llm','manual')),
	CONSTRAINT ck_strategy_assessments_frame_window_valid CHECK (frame_start >= 0 AND frame_end >= frame_start),
	CONSTRAINT ck_strategy_assessments_quality_valid CHECK (quality IN ('available','unavailable','partial')),
	CONSTRAINT ck_strategy_assessments_confidence_bounded CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
	CONSTRAINT fk_strategy_assessments_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT,
	CONSTRAINT fk_strategy_assessments_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_strategy_assessments_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_strategy_assessments_analysis_run_id_analysis_runs FOREIGN KEY(analysis_run_id) REFERENCES analysis_runs (id) ON DELETE SET NULL,
	CONSTRAINT uq_strategy_assessments_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE reports (
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER,
	analysis_run_id INTEGER,
	report_version VARCHAR(255) NOT NULL,
	input_digest VARCHAR(64) NOT NULL,
	cache_key VARCHAR(64) NOT NULL,
	report_json TEXT NOT NULL,
	structured_asset_id INTEGER,
	rendered_asset_id INTEGER,
	id INTEGER NOT NULL,
	public_id VARCHAR(36) NOT NULL CONSTRAINT ck_reports_public_id_lowercase_uuid CHECK (length(public_id) = 36 AND public_id = lower(public_id) AND substr(public_id, 9, 1) = '-' AND substr(public_id, 14, 1) = '-' AND substr(public_id, 19, 1) = '-' AND substr(public_id, 24, 1) = '-' AND length(replace(public_id, '-', '')) = 32 AND replace(public_id, '-', '') NOT GLOB '*[^0-9a-f]*'),
	created_at DATETIME NOT NULL,
	CONSTRAINT pk_reports PRIMARY KEY (id),
	CONSTRAINT ck_reports_input_digest_lowercase_sha256 CHECK (length(input_digest) = 64 AND input_digest = lower(input_digest) AND input_digest NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT ck_reports_cache_key_lowercase_sha256 CHECK (length(cache_key) = 64 AND cache_key = lower(cache_key) AND cache_key NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT uq_reports_replay_version_input UNIQUE (replay_id, report_version, input_digest),
	CONSTRAINT fk_reports_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE CASCADE,
	CONSTRAINT fk_reports_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE SET NULL,
	CONSTRAINT fk_reports_analysis_run_id_analysis_runs FOREIGN KEY(analysis_run_id) REFERENCES analysis_runs (id) ON DELETE SET NULL,
	CONSTRAINT fk_reports_structured_asset_id_managed_assets FOREIGN KEY(structured_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT fk_reports_rendered_asset_id_managed_assets FOREIGN KEY(rendered_asset_id) REFERENCES managed_assets (id) ON DELETE RESTRICT,
	CONSTRAINT uq_reports_public_id UNIQUE (public_id)
)""",
    r"""CREATE TABLE feature_evidence (
	feature_id INTEGER NOT NULL,
	evidence_item_id INTEGER NOT NULL,
	role VARCHAR(32) NOT NULL,
	CONSTRAINT pk_feature_evidence PRIMARY KEY (feature_id, evidence_item_id, role),
	CONSTRAINT ck_feature_evidence_role_valid CHECK (role IN ('input','supporting','contradicting')),
	CONSTRAINT fk_feature_evidence_feature_id_features FOREIGN KEY(feature_id) REFERENCES features (id) ON DELETE CASCADE,
	CONSTRAINT fk_feature_evidence_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT
)""",
    r"""CREATE TABLE assessment_evidence (
	assessment_id INTEGER NOT NULL,
	evidence_item_id INTEGER NOT NULL,
	role VARCHAR(32) NOT NULL,
	CONSTRAINT pk_assessment_evidence PRIMARY KEY (assessment_id, evidence_item_id, role),
	CONSTRAINT ck_assessment_evidence_role_valid CHECK (role IN ('supporting','contradicting')),
	CONSTRAINT fk_assessment_evidence_assessment_id_strategy_assessments FOREIGN KEY(assessment_id) REFERENCES strategy_assessments (id) ON DELETE CASCADE,
	CONSTRAINT fk_assessment_evidence_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT
)""",
    r"""CREATE TABLE longitudinal_members (
	longitudinal_result_id INTEGER NOT NULL,
	replay_id INTEGER NOT NULL,
	replay_player_id INTEGER NOT NULL,
	feature_set_id INTEGER NOT NULL,
	feature_id INTEGER,
	strategy_assessment_id INTEGER,
	evidence_item_id INTEGER NOT NULL,
	id INTEGER NOT NULL,
	CONSTRAINT pk_longitudinal_members PRIMARY KEY (id),
	CONSTRAINT uq_longitudinal_members_result_evidence UNIQUE (longitudinal_result_id, evidence_item_id),
	CONSTRAINT fk_longitudinal_members_longitudinal_result_id_longitudinal_results FOREIGN KEY(longitudinal_result_id) REFERENCES longitudinal_results (id) ON DELETE CASCADE,
	CONSTRAINT fk_longitudinal_members_replay_id_replays FOREIGN KEY(replay_id) REFERENCES replays (id) ON DELETE RESTRICT,
	CONSTRAINT fk_longitudinal_members_replay_player_id_replay_players FOREIGN KEY(replay_player_id) REFERENCES replay_players (id) ON DELETE RESTRICT,
	CONSTRAINT fk_longitudinal_members_feature_set_id_feature_sets FOREIGN KEY(feature_set_id) REFERENCES feature_sets (id) ON DELETE RESTRICT,
	CONSTRAINT fk_longitudinal_members_feature_id_features FOREIGN KEY(feature_id) REFERENCES features (id) ON DELETE RESTRICT,
	CONSTRAINT fk_longitudinal_members_strategy_assessment_id_strategy_assessments FOREIGN KEY(strategy_assessment_id) REFERENCES strategy_assessments (id) ON DELETE RESTRICT,
	CONSTRAINT fk_longitudinal_members_evidence_item_id_evidence_items FOREIGN KEY(evidence_item_id) REFERENCES evidence_items (id) ON DELETE RESTRICT
)""",
)

INDEX_DDL: tuple[str, ...] = (
    r"""CREATE INDEX ix_managed_assets_kind_created_at ON managed_assets (kind, created_at)""",
    r"""CREATE INDEX ix_maps_engine_data_map_identity ON maps (engine_data_identity, map_identity)""",
    r"""CREATE INDEX ix_maps_manifest_asset_id ON maps (manifest_asset_id)""",
    r"""CREATE INDEX ix_player_aliases_player_namespace ON player_aliases (player_id, namespace)""",
    r"""CREATE INDEX ix_player_aliases_player_id ON player_aliases (player_id)""",
    r"""CREATE INDEX ix_longitudinal_runs_player_id ON longitudinal_runs (player_id)""",
    r"""CREATE INDEX ix_longitudinal_runs_player_revision_status ON longitudinal_runs (player_id, identity_revision, status)""",
    r"""CREATE UNIQUE INDEX uq_longitudinal_runs_successful_cache_key ON longitudinal_runs (cache_key) WHERE status = 'succeeded'""",
    r"""CREATE INDEX ix_map_resources_map_resource_kind ON map_resources (map_id, resource_kind)""",
    r"""CREATE INDEX ix_map_resources_map_id ON map_resources (map_id)""",
    r"""CREATE INDEX ix_map_regions_map_region_kind ON map_regions (map_id, region_kind)""",
    r"""CREATE INDEX ix_map_regions_map_id ON map_regions (map_id)""",
    r"""CREATE INDEX ix_replays_managed_asset_id ON replays (managed_asset_id)""",
    r"""CREATE INDEX ix_replays_map_id ON replays (map_id)""",
    r"""CREATE INDEX ix_replays_lifecycle_map_version_start ON replays (lifecycle_state, map_id, version_number, start_time)""",
    r"""CREATE INDEX ix_sources_replay_id ON sources (replay_id)""",
    r"""CREATE INDEX ix_sources_strata_identity ON sources (strata_match_id, strata_source_user_token)""",
    r"""CREATE INDEX ix_sources_replay_discovered_at ON sources (replay_id, discovered_at)""",
    r"""CREATE INDEX ix_parser_runs_replay_id ON parser_runs (replay_id)""",
    r"""CREATE INDEX ix_parser_runs_replay_status_version ON parser_runs (replay_id, status, parser_version)""",
    r"""CREATE UNIQUE INDEX uq_parser_runs_successful_identity ON parser_runs (replay_id, parser_version, schema_version, input_sha256) WHERE status = 'succeeded'""",
    r"""CREATE INDEX ix_telemetry_runs_map_asset_id ON telemetry_runs (map_asset_id)""",
    r"""CREATE INDEX ix_telemetry_runs_catalog_asset_id ON telemetry_runs (catalog_asset_id)""",
    r"""CREATE INDEX ix_telemetry_runs_trace_asset_id ON telemetry_runs (trace_asset_id)""",
    r"""CREATE INDEX ix_telemetry_runs_replay_id ON telemetry_runs (replay_id)""",
    r"""CREATE INDEX ix_telemetry_runs_replay_status_started ON telemetry_runs (replay_id, status, started_at)""",
    r"""CREATE INDEX ix_telemetry_runs_map_id ON telemetry_runs (map_id)""",
    r"""CREATE INDEX ix_jobs_status_available_priority ON jobs (status, available_at, priority)""",
    r"""CREATE INDEX ix_jobs_status_lease_expires ON jobs (status, lease_expires_at)""",
    r"""CREATE INDEX ix_jobs_replay_id ON jobs (replay_id)""",
    r"""CREATE INDEX ix_replay_players_parser_run_id ON replay_players (parser_run_id)""",
    r"""CREATE INDEX ix_replay_players_player_id ON replay_players (player_id)""",
    r"""CREATE INDEX ix_replay_players_player_replay ON replay_players (player_id, replay_id)""",
    r"""CREATE INDEX ix_replay_players_replay_id ON replay_players (replay_id)""",
    r"""CREATE INDEX ix_replay_players_replay_player_index ON replay_players (replay_id, player_index)""",
    r"""CREATE INDEX ix_entities_replay_template_name ON entities (replay_id, template_name)""",
    r"""CREATE INDEX ix_entities_replay_initial_owner ON entities (replay_id, initial_owner_player_index)""",
    r"""CREATE INDEX ix_entities_replay_id ON entities (replay_id)""",
    r"""CREATE INDEX ix_entities_telemetry_run_id ON entities (telemetry_run_id)""",
    r"""CREATE INDEX ix_evidence_items_replay_tier_source ON evidence_items (replay_id, tier, source_kind)""",
    r"""CREATE INDEX ix_evidence_items_telemetry_run_id ON evidence_items (telemetry_run_id)""",
    r"""CREATE INDEX ix_evidence_items_parser_run_id ON evidence_items (parser_run_id)""",
    r"""CREATE INDEX ix_evidence_items_replay_id ON evidence_items (replay_id)""",
    r"""CREATE INDEX ix_job_dependencies_depends_on_job_id ON job_dependencies (depends_on_job_id)""",
    r"""CREATE INDEX ix_job_dependencies_job_id ON job_dependencies (job_id)""",
    r"""CREATE INDEX ix_replay_quality_issues_replay_code_detected ON replay_quality_issues (replay_id, issue_code, detected_at)""",
    r"""CREATE INDEX ix_replay_quality_issues_replay_id ON replay_quality_issues (replay_id)""",
    r"""CREATE INDEX ix_replay_quality_issues_parser_run_id ON replay_quality_issues (parser_run_id)""",
    r"""CREATE INDEX ix_replay_quality_issues_evidence_item_id ON replay_quality_issues (evidence_item_id)""",
    r"""CREATE INDEX ix_replay_quality_issues_telemetry_run_id ON replay_quality_issues (telemetry_run_id)""",
    r"""CREATE INDEX ix_commands_parser_run_id ON commands (parser_run_id)""",
    r"""CREATE INDEX ix_commands_replay_player_frame ON commands (replay_id, player_index, frame)""",
    r"""CREATE INDEX ix_commands_replay_id ON commands (replay_id)""",
    r"""CREATE INDEX ix_commands_evidence_item_id ON commands (evidence_item_id)""",
    r"""CREATE INDEX ix_commands_replay_player_id ON commands (replay_player_id)""",
    r"""CREATE INDEX ix_commands_replay_frame_message_type ON commands (replay_id, frame, message_type)""",
    r"""CREATE INDEX ix_commands_parser_start_offset ON commands (parser_run_id, start_offset)""",
    r"""CREATE INDEX ix_telemetry_events_telemetry_run_id ON telemetry_events (telemetry_run_id)""",
    r"""CREATE INDEX ix_telemetry_events_evidence_item_id ON telemetry_events (evidence_item_id)""",
    r"""CREATE INDEX ix_telemetry_events_run_frame_type ON telemetry_events (telemetry_run_id, frame, event_type)""",
    r"""CREATE INDEX ix_telemetry_events_run_type_frame ON telemetry_events (telemetry_run_id, event_type, frame)""",
    r"""CREATE INDEX ix_feature_sets_replay_player_id ON feature_sets (replay_player_id)""",
    r"""CREATE INDEX ix_feature_sets_replay_id ON feature_sets (replay_id)""",
    r"""CREATE UNIQUE INDEX uq_feature_sets_successful_cache_key ON feature_sets (cache_key) WHERE status = 'succeeded'""",
    r"""CREATE INDEX ix_feature_sets_replay_extractor_status ON feature_sets (replay_id, extractor_name, extractor_version, status)""",
    r"""CREATE INDEX ix_analysis_runs_raw_response_asset_id ON analysis_runs (raw_response_asset_id)""",
    r"""CREATE UNIQUE INDEX uq_analysis_runs_successful_cache_key ON analysis_runs (cache_key) WHERE status = 'succeeded'""",
    r"""CREATE INDEX ix_analysis_runs_replay_player_id ON analysis_runs (replay_player_id)""",
    r"""CREATE INDEX ix_analysis_runs_replay_id ON analysis_runs (replay_id)""",
    r"""CREATE INDEX ix_analysis_runs_replay_status_created ON analysis_runs (replay_id, status, created_at)""",
    r"""CREATE INDEX ix_longitudinal_results_longitudinal_run_id ON longitudinal_results (longitudinal_run_id)""",
    r"""CREATE INDEX ix_longitudinal_results_evidence_item_id ON longitudinal_results (evidence_item_id)""",
    r"""CREATE INDEX ix_longitudinal_results_run_result_name ON longitudinal_results (longitudinal_run_id, result_name)""",
    r"""CREATE INDEX ix_entity_samples_telemetry_run_id ON entity_samples (telemetry_run_id)""",
    r"""CREATE INDEX ix_entity_samples_entity_id ON entity_samples (entity_id)""",
    r"""CREATE INDEX ix_entity_samples_entity_frame ON entity_samples (entity_id, frame)""",
    r"""CREATE INDEX ix_entity_samples_telemetry_event_id ON entity_samples (telemetry_event_id)""",
    r"""CREATE INDEX ix_production_events_replay_player_id ON production_events (replay_player_id)""",
    r"""CREATE INDEX ix_production_events_telemetry_event_id ON production_events (telemetry_event_id)""",
    r"""CREATE INDEX ix_production_events_replay_id ON production_events (replay_id)""",
    r"""CREATE INDEX ix_production_events_run_type_frame ON production_events (telemetry_run_id, event_type, frame)""",
    r"""CREATE INDEX ix_production_events_producer_entity_id ON production_events (producer_entity_id)""",
    r"""CREATE INDEX ix_production_events_telemetry_run_id ON production_events (telemetry_run_id)""",
    r"""CREATE INDEX ix_production_events_replay_player_frame ON production_events (replay_id, replay_player_id, frame)""",
    r"""CREATE INDEX ix_economy_events_replay_player_id ON economy_events (replay_player_id)""",
    r"""CREATE INDEX ix_economy_events_dropoff_entity_id ON economy_events (dropoff_entity_id)""",
    r"""CREATE INDEX ix_economy_events_run_type_frame ON economy_events (telemetry_run_id, event_type, frame)""",
    r"""CREATE INDEX ix_economy_events_replay_player_frame ON economy_events (replay_id, replay_player_id, frame)""",
    r"""CREATE INDEX ix_economy_events_source_entity_id ON economy_events (source_entity_id)""",
    r"""CREATE INDEX ix_economy_events_telemetry_run_id ON economy_events (telemetry_run_id)""",
    r"""CREATE INDEX ix_economy_events_telemetry_event_id ON economy_events (telemetry_event_id)""",
    r"""CREATE INDEX ix_economy_events_collector_entity_id ON economy_events (collector_entity_id)""",
    r"""CREATE INDEX ix_economy_events_replay_id ON economy_events (replay_id)""",
    r"""CREATE INDEX ix_combat_events_attacker_frame ON combat_events (attacker_entity_id, frame)""",
    r"""CREATE INDEX ix_combat_events_victim_entity_id ON combat_events (victim_entity_id)""",
    r"""CREATE INDEX ix_combat_events_victim_replay_player_id ON combat_events (victim_replay_player_id)""",
    r"""CREATE INDEX ix_combat_events_attacker_entity_id ON combat_events (attacker_entity_id)""",
    r"""CREATE INDEX ix_combat_events_telemetry_run_id ON combat_events (telemetry_run_id)""",
    r"""CREATE INDEX ix_combat_events_attacker_replay_player_id ON combat_events (attacker_replay_player_id)""",
    r"""CREATE INDEX ix_combat_events_replay_frame_type ON combat_events (replay_id, frame, event_type)""",
    r"""CREATE INDEX ix_combat_events_victim_frame ON combat_events (victim_entity_id, frame)""",
    r"""CREATE INDEX ix_combat_events_telemetry_event_id ON combat_events (telemetry_event_id)""",
    r"""CREATE INDEX ix_combat_events_replay_id ON combat_events (replay_id)""",
    r"""CREATE INDEX ix_combat_events_source_entity_id ON combat_events (source_entity_id)""",
    r"""CREATE INDEX ix_features_entity_id ON features (entity_id)""",
    r"""CREATE INDEX ix_features_replay_player_id ON features (replay_player_id)""",
    r"""CREATE INDEX ix_features_name_scope_window ON features (name, scope_type, scope_key, frame_start, frame_end)""",
    r"""CREATE INDEX ix_features_feature_set_id ON features (feature_set_id)""",
    r"""CREATE INDEX ix_features_evidence_item_id ON features (evidence_item_id)""",
    r"""CREATE INDEX ix_strategy_assessments_replay_id ON strategy_assessments (replay_id)""",
    r"""CREATE INDEX ix_strategy_assessments_evidence_item_id ON strategy_assessments (evidence_item_id)""",
    r"""CREATE INDEX ix_strategy_assessments_replay_label_phase_method ON strategy_assessments (replay_id, strategy_label, phase, method)""",
    r"""CREATE INDEX ix_strategy_assessments_replay_player_id ON strategy_assessments (replay_player_id)""",
    r"""CREATE INDEX ix_strategy_assessments_analysis_run_id ON strategy_assessments (analysis_run_id)""",
    r"""CREATE INDEX ix_reports_replay_id ON reports (replay_id)""",
    r"""CREATE INDEX ix_reports_replay_created_at ON reports (replay_id, created_at)""",
    r"""CREATE INDEX ix_reports_structured_asset_id ON reports (structured_asset_id)""",
    r"""CREATE INDEX ix_reports_analysis_run_id ON reports (analysis_run_id)""",
    r"""CREATE INDEX ix_reports_replay_player_id ON reports (replay_player_id)""",
    r"""CREATE INDEX ix_reports_rendered_asset_id ON reports (rendered_asset_id)""",
    r"""CREATE INDEX ix_feature_evidence_feature_id ON feature_evidence (feature_id)""",
    r"""CREATE INDEX ix_feature_evidence_evidence_item_id ON feature_evidence (evidence_item_id)""",
    r"""CREATE INDEX ix_assessment_evidence_evidence_item_id ON assessment_evidence (evidence_item_id)""",
    r"""CREATE INDEX ix_assessment_evidence_assessment_id ON assessment_evidence (assessment_id)""",
    r"""CREATE INDEX ix_longitudinal_members_evidence_item_id ON longitudinal_members (evidence_item_id)""",
    r"""CREATE INDEX ix_longitudinal_members_replay_id ON longitudinal_members (replay_id)""",
    r"""CREATE INDEX ix_longitudinal_members_strategy_assessment_id ON longitudinal_members (strategy_assessment_id)""",
    r"""CREATE INDEX ix_longitudinal_members_longitudinal_result_id ON longitudinal_members (longitudinal_result_id)""",
    r"""CREATE INDEX ix_longitudinal_members_replay_player_id ON longitudinal_members (replay_player_id)""",
    r"""CREATE INDEX ix_longitudinal_members_feature_id ON longitudinal_members (feature_id)""",
    r"""CREATE INDEX ix_longitudinal_members_feature_set_id ON longitudinal_members (feature_set_id)""",
)

TRIGGER_DDL: tuple[str, ...] = (
    r"""CREATE TRIGGER trg_parser_runs_succeeded_no_update BEFORE UPDATE ON parser_runs WHEN OLD.status = 'succeeded' BEGIN SELECT RAISE(ABORT, 'successful observation run is immutable'); END""",
    r"""CREATE TRIGGER trg_parser_runs_succeeded_no_delete BEFORE DELETE ON parser_runs WHEN OLD.status = 'succeeded' BEGIN SELECT RAISE(ABORT, 'successful observation run is immutable'); END""",
    r"""CREATE TRIGGER trg_telemetry_runs_succeeded_no_update BEFORE UPDATE ON telemetry_runs WHEN OLD.status = 'succeeded' BEGIN SELECT RAISE(ABORT, 'successful observation run is immutable'); END""",
    r"""CREATE TRIGGER trg_telemetry_runs_succeeded_no_delete BEFORE DELETE ON telemetry_runs WHEN OLD.status = 'succeeded' BEGIN SELECT RAISE(ABORT, 'successful observation run is immutable'); END""",
    r"""CREATE TRIGGER trg_commands_succeeded_no_insert BEFORE INSERT ON commands WHEN EXISTS (SELECT 1 FROM parser_runs WHERE id = NEW.parser_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_commands_succeeded_no_update BEFORE UPDATE ON commands WHEN EXISTS (SELECT 1 FROM parser_runs WHERE id = OLD.parser_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM parser_runs WHERE id = NEW.parser_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_commands_succeeded_no_delete BEFORE DELETE ON commands WHEN EXISTS (SELECT 1 FROM parser_runs WHERE id = OLD.parser_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_telemetry_events_succeeded_no_insert BEFORE INSERT ON telemetry_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_telemetry_events_succeeded_no_update BEFORE UPDATE ON telemetry_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_telemetry_events_succeeded_no_delete BEFORE DELETE ON telemetry_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_entities_succeeded_no_insert BEFORE INSERT ON entities WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_entities_succeeded_no_update BEFORE UPDATE ON entities WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_entities_succeeded_no_delete BEFORE DELETE ON entities WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_entity_samples_succeeded_no_insert BEFORE INSERT ON entity_samples WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_entity_samples_succeeded_no_update BEFORE UPDATE ON entity_samples WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_entity_samples_succeeded_no_delete BEFORE DELETE ON entity_samples WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_production_events_succeeded_no_insert BEFORE INSERT ON production_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_production_events_succeeded_no_update BEFORE UPDATE ON production_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_production_events_succeeded_no_delete BEFORE DELETE ON production_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_economy_events_succeeded_no_insert BEFORE INSERT ON economy_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_economy_events_succeeded_no_update BEFORE UPDATE ON economy_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_economy_events_succeeded_no_delete BEFORE DELETE ON economy_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_combat_events_succeeded_no_insert BEFORE INSERT ON combat_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be appended'); END""",
    r"""CREATE TRIGGER trg_combat_events_succeeded_no_update BEFORE UPDATE ON combat_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be updated'); END""",
    r"""CREATE TRIGGER trg_combat_events_succeeded_no_delete BEFORE DELETE ON combat_events WHEN EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful observations cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_evidence_items_observed_no_insert BEFORE INSERT ON evidence_items WHEN NEW.tier = 'observed' AND (EXISTS (SELECT 1 FROM parser_runs WHERE id = NEW.parser_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded')) BEGIN SELECT RAISE(ABORT, 'successful observed evidence cannot be appended'); END""",
    r"""CREATE TRIGGER trg_evidence_items_observed_no_update BEFORE UPDATE ON evidence_items WHEN (OLD.tier = 'observed' AND (EXISTS (SELECT 1 FROM parser_runs WHERE id = OLD.parser_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded'))) OR (NEW.tier = 'observed' AND (EXISTS (SELECT 1 FROM parser_runs WHERE id = NEW.parser_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = NEW.telemetry_run_id AND status = 'succeeded'))) BEGIN SELECT RAISE(ABORT, 'successful observed evidence cannot be updated'); END""",
    r"""CREATE TRIGGER trg_evidence_items_observed_no_delete BEFORE DELETE ON evidence_items WHEN OLD.tier = 'observed' AND (EXISTS (SELECT 1 FROM parser_runs WHERE id = OLD.parser_run_id AND status = 'succeeded') OR EXISTS (SELECT 1 FROM telemetry_runs WHERE id = OLD.telemetry_run_id AND status = 'succeeded')) BEGIN SELECT RAISE(ABORT, 'successful observed evidence cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_replay_players_succeeded_no_insert BEFORE INSERT ON replay_players WHEN EXISTS (SELECT 1 FROM parser_runs WHERE id = NEW.parser_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful parser player evidence cannot be appended'); END""",
    r"""CREATE TRIGGER trg_replay_players_succeeded_no_delete BEFORE DELETE ON replay_players WHEN EXISTS (SELECT 1 FROM parser_runs WHERE id = OLD.parser_run_id AND status = 'succeeded') BEGIN SELECT RAISE(ABORT, 'successful parser player evidence cannot be deleted'); END""",
    r"""CREATE TRIGGER trg_replay_players_succeeded_no_observation_update BEFORE UPDATE ON replay_players WHEN (EXISTS (SELECT 1 FROM parser_runs WHERE id = OLD.parser_run_id AND status = 'succeeded')) AND (NEW.public_id IS NOT OLD.public_id OR NEW.replay_id IS NOT OLD.replay_id OR NEW.parser_run_id IS NOT OLD.parser_run_id OR NEW.slot_index IS NOT OLD.slot_index OR NEW.slot_kind IS NOT OLD.slot_kind OR NEW.original_name IS NOT OLD.original_name OR NEW.normalized_name IS NOT OLD.normalized_name OR NEW.player_index IS NOT OLD.player_index OR NEW.team_id IS NOT OLD.team_id OR NEW.faction IS NOT OLD.faction OR NEW.color IS NOT OLD.color OR NEW.start_position IS NOT OLD.start_position OR NEW.result IS NOT OLD.result OR NEW.observed_json IS NOT OLD.observed_json) BEGIN SELECT RAISE(ABORT, 'successful parser player observations cannot be updated'); END""",
)

TABLE_NAMES: tuple[str, ...] = (
    "managed_assets",
    "players",
    "maps",
    "player_aliases",
    "longitudinal_runs",
    "map_resources",
    "map_regions",
    "replays",
    "sources",
    "parser_runs",
    "telemetry_runs",
    "jobs",
    "replay_players",
    "entities",
    "evidence_items",
    "job_dependencies",
    "replay_quality_issues",
    "commands",
    "telemetry_events",
    "feature_sets",
    "analysis_runs",
    "longitudinal_results",
    "entity_samples",
    "production_events",
    "economy_events",
    "combat_events",
    "features",
    "strategy_assessments",
    "reports",
    "feature_evidence",
    "assessment_evidence",
    "longitudinal_members",
)
TRIGGER_NAMES: tuple[str, ...] = ('trg_parser_runs_succeeded_no_update', 'trg_parser_runs_succeeded_no_delete', 'trg_telemetry_runs_succeeded_no_update', 'trg_telemetry_runs_succeeded_no_delete', 'trg_commands_succeeded_no_insert', 'trg_commands_succeeded_no_update', 'trg_commands_succeeded_no_delete', 'trg_telemetry_events_succeeded_no_insert', 'trg_telemetry_events_succeeded_no_update', 'trg_telemetry_events_succeeded_no_delete', 'trg_entities_succeeded_no_insert', 'trg_entities_succeeded_no_update', 'trg_entities_succeeded_no_delete', 'trg_entity_samples_succeeded_no_insert', 'trg_entity_samples_succeeded_no_update', 'trg_entity_samples_succeeded_no_delete', 'trg_production_events_succeeded_no_insert', 'trg_production_events_succeeded_no_update', 'trg_production_events_succeeded_no_delete', 'trg_economy_events_succeeded_no_insert', 'trg_economy_events_succeeded_no_update', 'trg_economy_events_succeeded_no_delete', 'trg_combat_events_succeeded_no_insert', 'trg_combat_events_succeeded_no_update', 'trg_combat_events_succeeded_no_delete', 'trg_evidence_items_observed_no_insert', 'trg_evidence_items_observed_no_update', 'trg_evidence_items_observed_no_delete', 'trg_replay_players_succeeded_no_insert', 'trg_replay_players_succeeded_no_delete', 'trg_replay_players_succeeded_no_observation_update')


# TheSuperHackers @feature Leex 21/08/2026 Keep revision 0001 independent of mutable application metadata. (#TBD)
def upgrade() -> None:
    for statement in (*TABLE_DDL, *INDEX_DDL, *TRIGGER_DDL):
        op.execute(statement)


def downgrade() -> None:
    for name in reversed(TRIGGER_NAMES):
        op.execute(f'DROP TRIGGER IF EXISTS "{name}"')
    for name in reversed(TABLE_NAMES):
        op.execute(f'DROP TABLE IF EXISTS "{name}"')
